language: node_js

node_js:
  - '8'

env:
  global:
    - COVERALLS_PARALLEL=true

jobs:
  include:
    - script: WEBPACK_VERSION=V4 && npm run test && npm run coveralls
    - script: WEBPACK_VERSION=V3 && npm run test && npm run coveralls
    - script: WEBPACK_VERSION=V2 && npm run test && npm run coveralls

before_install:
  - if [ "$WEBPACK_VERSION" = "V3" ]; then  rm -f package-lock.json; sed "s/\"webpack\":\s*\"4\.[0-9]\+\.[0-9]\+\"/\"webpack\":\"3.11.0\"/" package.json >package.webpack3.json; cp -f ./package.webpack3.json ./package.json; fi
  - if [ "$WEBPACK_VERSION" = "V2" ]; then  rm -f package-lock.json; sed "s/\"webpack\":\s*\"4\.[0-9]\+\.[0-9]\+\"/\"webpack\":\"2.6.0\"/" package.json >package.webpack2.json; cp -f ./package.webpack2.json ./package.json; fi
cache:
  directories:
    - node_modules

sudo: false

notifications:
  webhooks: https://coveralls.io/webhook
